/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactRequest {
  'id' : string,
  'status' : string,
  'projectType' : [] | [string],
  'name' : string,
  'submittedAt' : Time,
  'submittedBy' : Principal,
  'description' : string,
  'productId' : [] | [string],
  'email' : string,
  'budget' : [] | [string],
  'timeline' : [] | [string],
}
export interface Coupon {
  'active' : boolean,
  'validFrom' : Time,
  'code' : string,
  'discountType' : CouponType,
  'usageCount' : bigint,
  'usageLimit' : [] | [bigint],
  'validUntil' : Time,
}
export type CouponType = { 'fixed' : bigint } |
  { 'percentage' : bigint };
export interface FulfillmentOptions {
  'dropoff' : boolean,
  'pickup' : boolean,
  'shippingEnabled' : boolean,
  'delivery' : boolean,
}
export interface Giveaway {
  'id' : string,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'entrants' : Array<GiveawayEntrant>,
  'winners' : Array<GiveawayWinner>,
}
export interface GiveawayEntrant {
  'principal' : Principal,
  'displayName' : string,
  'enteredAt' : Time,
}
export interface GiveawayWinner {
  'giveawayId' : string,
  'entrant' : GiveawayEntrant,
  'wonAt' : Time,
}
export type LoyaltyAction = { 'visit' : null } |
  { 'share' : null } |
  { 'signup' : null } |
  { 'purchase' : bigint };
export interface LoyaltyReward {
  'id' : string,
  'active' : boolean,
  'pointsRequired' : bigint,
  'rewardValue' : string,
  'name' : string,
  'rewardType' : string,
}
export interface Policies {
  'serviceArea' : string,
  'returnPolicy' : string,
  'shippingPolicy' : string,
}
export interface PortfolioItem {
  'id' : string,
  'media' : PortfolioMedia,
  'title' : string,
  'description' : string,
  'category' : [] | [string],
}
export type PortfolioMedia = { 'video' : Uint8Array } |
  { 'image' : Uint8Array };
export interface Product {
  'id' : string,
  'requiresQuote' : boolean,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'category' : [] | [string],
  'image' : Uint8Array,
  'price' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SocialMediaLink { 'url' : string, 'platform' : string }
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Testimonial {
  'id' : string,
  'content' : string,
  'createdAt' : Time,
  'author' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'loyaltyPoints' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGiveawayEntrant' : ActorMethod<[string, string], undefined>,
  'addGiveawayEntrantByAdmin' : ActorMethod<
    [string, Principal, string],
    undefined
  >,
  'addLoyaltyPoints' : ActorMethod<[LoyaltyAction], bigint>,
  'addPortfolioItem' : ActorMethod<[PortfolioItem], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addSocialMediaLink' : ActorMethod<[string, string], undefined>,
  'addTestimonial' : ActorMethod<[Testimonial], undefined>,
  'applyCoupon' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCoupon' : ActorMethod<[Coupon], undefined>,
  'createGiveaway' : ActorMethod<[Giveaway], undefined>,
  'createLoyaltyReward' : ActorMethod<[LoyaltyReward], undefined>,
  'deletePortfolioItem' : ActorMethod<[string], undefined>,
  'getActiveGiveaways' : ActorMethod<[], Array<Giveaway>>,
  'getAdminVerificationStatus' : ActorMethod<
    [],
    {
      'failed_attempts' : bigint,
      'remaining_attempts' : [] | [bigint],
      'permanently_locked' : boolean,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactRequests' : ActorMethod<[], Array<ContactRequest>>,
  'getCoupons' : ActorMethod<[], Array<Coupon>>,
  'getFulfillmentOptions' : ActorMethod<[], FulfillmentOptions>,
  'getGiveaway' : ActorMethod<[string], [] | [Giveaway]>,
  'getLoyaltyPoints' : ActorMethod<[], bigint>,
  'getLoyaltyRewards' : ActorMethod<[], Array<LoyaltyReward>>,
  'getMyContactRequests' : ActorMethod<[], Array<ContactRequest>>,
  'getPolicies' : ActorMethod<[], Policies>,
  'getPortfolioItem' : ActorMethod<[string], [] | [PortfolioItem]>,
  'getPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSocialMediaLinks' : ActorMethod<[], Array<SocialMediaLink>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTestimonial' : ActorMethod<[string], [] | [Testimonial]>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantUserAccess' : ActorMethod<[Principal], undefined>,
  'hasValidAdminSession' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPermanentlyLocked' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAdminUsers' : ActorMethod<[], Array<Principal>>,
  'migrateLegacyPortfolioItems' : ActorMethod<[], undefined>,
  'redeemLoyaltyReward' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selectGiveawayWinner' : ActorMethod<[string, bigint], [] | [GiveawayWinner]>,
  'setFulfillmentOptions' : ActorMethod<[FulfillmentOptions], undefined>,
  'setPolicies' : ActorMethod<[Policies], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContactRequest' : ActorMethod<[ContactRequest], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateContactRequestStatus' : ActorMethod<[string, string], undefined>,
  'updateMasterOverride' : ActorMethod<[string, string], undefined>,
  'updateWithMasterOverride' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'validateCoupon' : ActorMethod<[string], [] | [Coupon]>,
  'verifyAdminCodeStep1' : ActorMethod<[string], boolean>,
  'verifyAdminCodeStep2' : ActorMethod<[string], boolean>,
  'verifyAdminCodeStep3' : ActorMethod<[string], boolean>,
  'verifyAdminMasterOverride' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];