/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const LoyaltyAction = IDL.Variant({
  'visit' : IDL.Null,
  'share' : IDL.Null,
  'signup' : IDL.Null,
  'purchase' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PortfolioItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'image' : ExternalBlob,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'requiresQuote' : IDL.Bool,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CouponType = IDL.Variant({
  'fixed' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const Coupon = IDL.Record({
  'active' : IDL.Bool,
  'validFrom' : Time,
  'code' : IDL.Text,
  'discountType' : CouponType,
  'usageCount' : IDL.Nat,
  'usageLimit' : IDL.Opt(IDL.Nat),
  'validUntil' : Time,
});
export const GiveawayEntrant = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'enteredAt' : Time,
});
export const GiveawayWinner = IDL.Record({
  'giveawayId' : IDL.Text,
  'entrant' : GiveawayEntrant,
  'wonAt' : Time,
});
export const Giveaway = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'entrants' : IDL.Vec(GiveawayEntrant),
  'winners' : IDL.Vec(GiveawayWinner),
});
export const LoyaltyReward = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'pointsRequired' : IDL.Nat,
  'rewardValue' : IDL.Text,
  'name' : IDL.Text,
  'rewardType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'loyaltyPoints' : IDL.Nat,
});
export const ContactRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'projectType' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'submittedAt' : Time,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'productId' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'budget' : IDL.Opt(IDL.Text),
  'timeline' : IDL.Opt(IDL.Text),
});
export const FulfillmentOptions = IDL.Record({
  'dropoff' : IDL.Bool,
  'pickup' : IDL.Bool,
  'shippingEnabled' : IDL.Bool,
  'delivery' : IDL.Bool,
});
export const Policies = IDL.Record({
  'serviceArea' : IDL.Text,
  'returnPolicy' : IDL.Text,
  'shippingPolicy' : IDL.Text,
});
export const SocialMediaLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGiveawayEntrant' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addGiveawayEntrantByAdmin' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text],
      [],
      [],
    ),
  'addLoyaltyPoints' : IDL.Func([LoyaltyAction], [IDL.Nat], []),
  'addPortfolioItem' : IDL.Func([PortfolioItem], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addSocialMediaLink' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addTestimonial' : IDL.Func([Testimonial], [], []),
  'applyCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCoupon' : IDL.Func([Coupon], [], []),
  'createGiveaway' : IDL.Func([Giveaway], [], []),
  'createLoyaltyReward' : IDL.Func([LoyaltyReward], [], []),
  'getActiveGiveaways' : IDL.Func([], [IDL.Vec(Giveaway)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getFulfillmentOptions' : IDL.Func([], [FulfillmentOptions], ['query']),
  'getGiveaway' : IDL.Func([IDL.Text], [IDL.Opt(Giveaway)], ['query']),
  'getLoyaltyPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getLoyaltyRewards' : IDL.Func([], [IDL.Vec(LoyaltyReward)], ['query']),
  'getMyContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getPolicies' : IDL.Func([], [Policies], ['query']),
  'getPortfolioItem' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PortfolioItem)],
      ['query'],
    ),
  'getPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSocialMediaLinks' : IDL.Func([], [IDL.Vec(SocialMediaLink)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTestimonial' : IDL.Func([IDL.Text], [IDL.Opt(Testimonial)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantUserAccess' : IDL.Func([IDL.Principal], [], []),
  'hasValidAdminSession' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdminUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'recordPurchase' : IDL.Func([IDL.Nat], [], []),
  'redeemLoyaltyReward' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selectGiveawayWinner' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(GiveawayWinner)],
      [],
    ),
  'setFulfillmentOptions' : IDL.Func([FulfillmentOptions], [], []),
  'setPolicies' : IDL.Func([Policies], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitContactRequest' : IDL.Func([ContactRequest], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateContactRequestStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], []),
  'verifyAdminCodeStep1' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'verifyAdminCodeStep2' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'verifyAdminCodeStep3' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const LoyaltyAction = IDL.Variant({
    'visit' : IDL.Null,
    'share' : IDL.Null,
    'signup' : IDL.Null,
    'purchase' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PortfolioItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'image' : ExternalBlob,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'requiresQuote' : IDL.Bool,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CouponType = IDL.Variant({ 'fixed' : IDL.Nat, 'percentage' : IDL.Nat });
  const Coupon = IDL.Record({
    'active' : IDL.Bool,
    'validFrom' : Time,
    'code' : IDL.Text,
    'discountType' : CouponType,
    'usageCount' : IDL.Nat,
    'usageLimit' : IDL.Opt(IDL.Nat),
    'validUntil' : Time,
  });
  const GiveawayEntrant = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'enteredAt' : Time,
  });
  const GiveawayWinner = IDL.Record({
    'giveawayId' : IDL.Text,
    'entrant' : GiveawayEntrant,
    'wonAt' : Time,
  });
  const Giveaway = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'entrants' : IDL.Vec(GiveawayEntrant),
    'winners' : IDL.Vec(GiveawayWinner),
  });
  const LoyaltyReward = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'pointsRequired' : IDL.Nat,
    'rewardValue' : IDL.Text,
    'name' : IDL.Text,
    'rewardType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'loyaltyPoints' : IDL.Nat,
  });
  const ContactRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'projectType' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'submittedAt' : Time,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'productId' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'budget' : IDL.Opt(IDL.Text),
    'timeline' : IDL.Opt(IDL.Text),
  });
  const FulfillmentOptions = IDL.Record({
    'dropoff' : IDL.Bool,
    'pickup' : IDL.Bool,
    'shippingEnabled' : IDL.Bool,
    'delivery' : IDL.Bool,
  });
  const Policies = IDL.Record({
    'serviceArea' : IDL.Text,
    'returnPolicy' : IDL.Text,
    'shippingPolicy' : IDL.Text,
  });
  const SocialMediaLink = IDL.Record({
    'url' : IDL.Text,
    'platform' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGiveawayEntrant' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addGiveawayEntrantByAdmin' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text],
        [],
        [],
      ),
    'addLoyaltyPoints' : IDL.Func([LoyaltyAction], [IDL.Nat], []),
    'addPortfolioItem' : IDL.Func([PortfolioItem], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addSocialMediaLink' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addTestimonial' : IDL.Func([Testimonial], [], []),
    'applyCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCoupon' : IDL.Func([Coupon], [], []),
    'createGiveaway' : IDL.Func([Giveaway], [], []),
    'createLoyaltyReward' : IDL.Func([LoyaltyReward], [], []),
    'getActiveGiveaways' : IDL.Func([], [IDL.Vec(Giveaway)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
    'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getFulfillmentOptions' : IDL.Func([], [FulfillmentOptions], ['query']),
    'getGiveaway' : IDL.Func([IDL.Text], [IDL.Opt(Giveaway)], ['query']),
    'getLoyaltyPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getLoyaltyRewards' : IDL.Func([], [IDL.Vec(LoyaltyReward)], ['query']),
    'getMyContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
    'getPolicies' : IDL.Func([], [Policies], ['query']),
    'getPortfolioItem' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PortfolioItem)],
        ['query'],
      ),
    'getPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSocialMediaLinks' : IDL.Func([], [IDL.Vec(SocialMediaLink)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTestimonial' : IDL.Func([IDL.Text], [IDL.Opt(Testimonial)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantUserAccess' : IDL.Func([IDL.Principal], [], []),
    'hasValidAdminSession' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdminUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'recordPurchase' : IDL.Func([IDL.Nat], [], []),
    'redeemLoyaltyReward' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selectGiveawayWinner' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(GiveawayWinner)],
        [],
      ),
    'setFulfillmentOptions' : IDL.Func([FulfillmentOptions], [], []),
    'setPolicies' : IDL.Func([Policies], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitContactRequest' : IDL.Func([ContactRequest], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateContactRequestStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], []),
    'verifyAdminCodeStep1' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'verifyAdminCodeStep2' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'verifyAdminCodeStep3' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };