/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Testimonial {
    id: string;
    content: string;
    createdAt: Time;
    author: string;
    rating: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface Policies {
    serviceArea: string;
    returnPolicy: string;
    shippingPolicy: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface GiveawayEntrant {
    principal: Principal;
    displayName: string;
    enteredAt: Time;
}
export interface SocialMediaLink {
    url: string;
    platform: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FulfillmentOptions {
    dropoff: boolean;
    pickup: boolean;
    shippingEnabled: boolean;
    delivery: boolean;
}
export interface ContactRequest {
    id: string;
    status: string;
    projectType?: string;
    name: string;
    submittedAt: Time;
    submittedBy: Principal;
    description: string;
    productId?: string;
    email: string;
    budget?: string;
    timeline?: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type LoyaltyAction = {
    __kind__: "visit";
    visit: null;
} | {
    __kind__: "share";
    share: null;
} | {
    __kind__: "signup";
    signup: null;
} | {
    __kind__: "purchase";
    purchase: bigint;
};
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Coupon {
    active: boolean;
    validFrom: Time;
    code: string;
    discountType: CouponType;
    usageCount: bigint;
    usageLimit?: bigint;
    validUntil: Time;
}
export interface GiveawayWinner {
    giveawayId: string;
    entrant: GiveawayEntrant;
    wonAt: Time;
}
export interface Giveaway {
    id: string;
    active: boolean;
    name: string;
    description: string;
    entrants: Array<GiveawayEntrant>;
    winners: Array<GiveawayWinner>;
}
export type CouponType = {
    __kind__: "fixed";
    fixed: bigint;
} | {
    __kind__: "percentage";
    percentage: bigint;
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface PortfolioItem {
    id: string;
    title: string;
    description: string;
    category?: string;
    image: ExternalBlob;
}
export interface LoyaltyReward {
    id: string;
    active: boolean;
    pointsRequired: bigint;
    rewardValue: string;
    name: string;
    rewardType: string;
}
export interface UserProfile {
    name: string;
    email?: string;
    loyaltyPoints: bigint;
}
export interface Product {
    id: string;
    requiresQuote: boolean;
    inStock: boolean;
    name: string;
    description: string;
    category?: string;
    image: ExternalBlob;
    price: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGiveawayEntrant(giveawayId: string, displayName: string): Promise<void>;
    addGiveawayEntrantByAdmin(giveawayId: string, userPrincipal: Principal, displayName: string): Promise<void>;
    addLoyaltyPoints(action: LoyaltyAction): Promise<bigint>;
    addPortfolioItem(item: PortfolioItem): Promise<void>;
    addProduct(product: Product): Promise<void>;
    addSocialMediaLink(platform: string, url: string): Promise<void>;
    addTestimonial(testimonial: Testimonial): Promise<void>;
    applyCoupon(code: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createCoupon(coupon: Coupon): Promise<void>;
    createGiveaway(giveaway: Giveaway): Promise<void>;
    createLoyaltyReward(reward: LoyaltyReward): Promise<void>;
    deleteCoupon(code: string): Promise<void>;
    deleteGiveaway(id: string): Promise<void>;
    deleteLoyaltyReward(id: string): Promise<void>;
    deletePortfolioItem(id: string): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    deleteSocialMediaLink(platform: string): Promise<void>;
    deleteTestimonial(id: string): Promise<void>;
    getActiveGiveaways(): Promise<Array<Giveaway>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactRequests(): Promise<Array<ContactRequest>>;
    getCoupons(): Promise<Array<Coupon>>;
    getFulfillmentOptions(): Promise<FulfillmentOptions>;
    getGiveaway(id: string): Promise<Giveaway | null>;
    getLoyaltyPoints(): Promise<bigint>;
    getLoyaltyRewards(): Promise<Array<LoyaltyReward>>;
    getMyContactRequests(): Promise<Array<ContactRequest>>;
    getPolicies(): Promise<Policies>;
    getPortfolioItem(id: string): Promise<PortfolioItem | null>;
    getPortfolioItems(): Promise<Array<PortfolioItem>>;
    getProduct(id: string): Promise<Product | null>;
    getProducts(): Promise<Array<Product>>;
    getSocialMediaLinks(): Promise<Array<SocialMediaLink>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTestimonial(id: string): Promise<Testimonial | null>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantAdminAccess(user: Principal): Promise<void>;
    hasValidAdminSharedCode(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAdminUsers(): Promise<Array<Principal>>;
    recordPurchase(amount: bigint): Promise<void>;
    redeemLoyaltyReward(rewardId: string): Promise<boolean>;
    retryVerifyAdminSharedCode(code: string): Promise<boolean>;
    revokeAdminAccess(user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    selectGiveawayWinner(giveawayId: string, winnerIndex: bigint): Promise<GiveawayWinner | null>;
    setFulfillmentOptions(options: FulfillmentOptions): Promise<void>;
    setPolicies(newPolicies: Policies): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitContactRequest(request: ContactRequest): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateContactRequestStatus(id: string, status: string): Promise<void>;
    updateCoupon(coupon: Coupon): Promise<void>;
    updateGiveaway(giveaway: Giveaway): Promise<void>;
    updateLoyaltyReward(reward: LoyaltyReward): Promise<void>;
    updatePortfolioItem(item: PortfolioItem): Promise<void>;
    updateProduct(product: Product): Promise<void>;
    updateSocialMediaLink(platform: string, url: string): Promise<void>;
    updateTestimonial(testimonial: Testimonial): Promise<void>;
    validateCoupon(code: string): Promise<Coupon | null>;
    verifyAdminSharedCode(code: string): Promise<boolean>;
}
import type { ContactRequest as _ContactRequest, Coupon as _Coupon, CouponType as _CouponType, ExternalBlob as _ExternalBlob, Giveaway as _Giveaway, GiveawayWinner as _GiveawayWinner, LoyaltyAction as _LoyaltyAction, PortfolioItem as _PortfolioItem, Product as _Product, StripeSessionStatus as _StripeSessionStatus, Testimonial as _Testimonial, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGiveawayEntrant(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGiveawayEntrant(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGiveawayEntrant(arg0, arg1);
            return result;
        }
    }
    async addGiveawayEntrantByAdmin(arg0: string, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGiveawayEntrantByAdmin(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGiveawayEntrantByAdmin(arg0, arg1, arg2);
            return result;
        }
    }
    async addLoyaltyPoints(arg0: LoyaltyAction): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLoyaltyPoints(to_candid_LoyaltyAction_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLoyaltyPoints(to_candid_LoyaltyAction_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPortfolioItem(arg0: PortfolioItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPortfolioItem(await to_candid_PortfolioItem_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPortfolioItem(await to_candid_PortfolioItem_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSocialMediaLink(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSocialMediaLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSocialMediaLink(arg0, arg1);
            return result;
        }
    }
    async addTestimonial(arg0: Testimonial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0);
            return result;
        }
    }
    async applyCoupon(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.applyCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyCoupon(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createCoupon(arg0: Coupon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoupon(to_candid_Coupon_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoupon(to_candid_Coupon_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createGiveaway(arg0: Giveaway): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGiveaway(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGiveaway(arg0);
            return result;
        }
    }
    async createLoyaltyReward(arg0: LoyaltyReward): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLoyaltyReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLoyaltyReward(arg0);
            return result;
        }
    }
    async deleteCoupon(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoupon(arg0);
            return result;
        }
    }
    async deleteGiveaway(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGiveaway(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGiveaway(arg0);
            return result;
        }
    }
    async deleteLoyaltyReward(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLoyaltyReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLoyaltyReward(arg0);
            return result;
        }
    }
    async deletePortfolioItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePortfolioItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePortfolioItem(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteSocialMediaLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSocialMediaLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSocialMediaLink(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async getActiveGiveaways(): Promise<Array<Giveaway>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveGiveaways();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveGiveaways();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactRequests(): Promise<Array<ContactRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactRequests();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactRequests();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoupons();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoupons();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFulfillmentOptions(): Promise<FulfillmentOptions> {
        if (this.processError) {
            try {
                const result = await this.actor.getFulfillmentOptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFulfillmentOptions();
            return result;
        }
    }
    async getGiveaway(arg0: string): Promise<Giveaway | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGiveaway(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGiveaway(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoyaltyPoints(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoyaltyPoints();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoyaltyPoints();
            return result;
        }
    }
    async getLoyaltyRewards(): Promise<Array<LoyaltyReward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoyaltyRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoyaltyRewards();
            return result;
        }
    }
    async getMyContactRequests(): Promise<Array<ContactRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyContactRequests();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyContactRequests();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPolicies(): Promise<Policies> {
        if (this.processError) {
            try {
                const result = await this.actor.getPolicies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPolicies();
            return result;
        }
    }
    async getPortfolioItem(arg0: string): Promise<PortfolioItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioItem(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioItem(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioItems(): Promise<Array<PortfolioItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioItems();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioItems();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSocialMediaLinks(): Promise<Array<SocialMediaLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSocialMediaLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSocialMediaLinks();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonial(arg0: string): Promise<Testimonial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonial(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonial(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantAdminAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantAdminAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantAdminAccess(arg0);
            return result;
        }
    }
    async hasValidAdminSharedCode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasValidAdminSharedCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasValidAdminSharedCode();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAdminUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdminUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdminUsers();
            return result;
        }
    }
    async recordPurchase(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPurchase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPurchase(arg0);
            return result;
        }
    }
    async redeemLoyaltyReward(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemLoyaltyReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemLoyaltyReward(arg0);
            return result;
        }
    }
    async retryVerifyAdminSharedCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.retryVerifyAdminSharedCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retryVerifyAdminSharedCode(arg0);
            return result;
        }
    }
    async revokeAdminAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeAdminAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeAdminAccess(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async selectGiveawayWinner(arg0: string, arg1: bigint): Promise<GiveawayWinner | null> {
        if (this.processError) {
            try {
                const result = await this.actor.selectGiveawayWinner(arg0, arg1);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectGiveawayWinner(arg0, arg1);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async setFulfillmentOptions(arg0: FulfillmentOptions): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFulfillmentOptions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFulfillmentOptions(arg0);
            return result;
        }
    }
    async setPolicies(arg0: Policies): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPolicies(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPolicies(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitContactRequest(arg0: ContactRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactRequest(to_candid_ContactRequest_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactRequest(to_candid_ContactRequest_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateContactRequestStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactRequestStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactRequestStatus(arg0, arg1);
            return result;
        }
    }
    async updateCoupon(arg0: Coupon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoupon(to_candid_Coupon_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoupon(to_candid_Coupon_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateGiveaway(arg0: Giveaway): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGiveaway(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGiveaway(arg0);
            return result;
        }
    }
    async updateLoyaltyReward(arg0: LoyaltyReward): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLoyaltyReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLoyaltyReward(arg0);
            return result;
        }
    }
    async updatePortfolioItem(arg0: PortfolioItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePortfolioItem(await to_candid_PortfolioItem_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePortfolioItem(await to_candid_PortfolioItem_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(await to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(await to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSocialMediaLink(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSocialMediaLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSocialMediaLink(arg0, arg1);
            return result;
        }
    }
    async updateTestimonial(arg0: Testimonial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonial(arg0);
            return result;
        }
    }
    async validateCoupon(arg0: string): Promise<Coupon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyAdminSharedCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminSharedCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminSharedCode(arg0);
            return result;
        }
    }
}
function from_candid_ContactRequest_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactRequest): ContactRequest {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_CouponType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CouponType): CouponType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Coupon_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coupon): Coupon {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_PortfolioItem_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioItem): Promise<PortfolioItem> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Giveaway]): Giveaway | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PortfolioItem]): Promise<PortfolioItem | null> {
    return value.length === 0 ? null : await from_candid_PortfolioItem_n37(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Testimonial]): Testimonial | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GiveawayWinner]): GiveawayWinner | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coupon]): Coupon | null {
    return value.length === 0 ? null : from_candid_Coupon_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    loyaltyPoints: bigint;
}): {
    name: string;
    email?: string;
    loyaltyPoints: bigint;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.email)),
        loyaltyPoints: value.loyaltyPoints
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    projectType: [] | [string];
    name: string;
    submittedAt: _Time;
    submittedBy: Principal;
    description: string;
    productId: [] | [string];
    email: string;
    budget: [] | [string];
    timeline: [] | [string];
}): {
    id: string;
    status: string;
    projectType?: string;
    name: string;
    submittedAt: Time;
    submittedBy: Principal;
    description: string;
    productId?: string;
    email: string;
    budget?: string;
    timeline?: string;
} {
    return {
        id: value.id,
        status: value.status,
        projectType: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.projectType)),
        name: value.name,
        submittedAt: value.submittedAt,
        submittedBy: value.submittedBy,
        description: value.description,
        productId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.productId)),
        email: value.email,
        budget: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.budget)),
        timeline: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.timeline))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    validFrom: _Time;
    code: string;
    discountType: _CouponType;
    usageCount: bigint;
    usageLimit: [] | [bigint];
    validUntil: _Time;
}): {
    active: boolean;
    validFrom: Time;
    code: string;
    discountType: CouponType;
    usageCount: bigint;
    usageLimit?: bigint;
    validUntil: Time;
} {
    return {
        active: value.active,
        validFrom: value.validFrom,
        code: value.code,
        discountType: from_candid_CouponType_n33(_uploadFile, _downloadFile, value.discountType),
        usageCount: value.usageCount,
        usageLimit: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.usageLimit)),
        validUntil: value.validUntil
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    category: [] | [string];
    image: _ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    description: string;
    category?: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        category: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.category)),
        image: await from_candid_ExternalBlob_n39(_uploadFile, _downloadFile, value.image)
    };
}
async function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    requiresQuote: boolean;
    inStock: boolean;
    name: string;
    description: string;
    category: [] | [string];
    image: _ExternalBlob;
    price: bigint;
}): Promise<{
    id: string;
    requiresQuote: boolean;
    inStock: boolean;
    name: string;
    description: string;
    category?: string;
    image: ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        requiresQuote: value.requiresQuote,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        category: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.category)),
        image: await from_candid_ExternalBlob_n39(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fixed: bigint;
} | {
    percentage: bigint;
}): {
    __kind__: "fixed";
    fixed: bigint;
} | {
    __kind__: "percentage";
    percentage: bigint;
} {
    return "fixed" in value ? {
        __kind__: "fixed",
        fixed: value.fixed
    } : "percentage" in value ? {
        __kind__: "percentage",
        percentage: value.percentage
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n47(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactRequest>): Array<ContactRequest> {
    return value.map((x)=>from_candid_ContactRequest_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Coupon>): Array<Coupon> {
    return value.map((x)=>from_candid_Coupon_n31(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PortfolioItem>): Promise<Array<PortfolioItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PortfolioItem_n37(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n42(_uploadFile, _downloadFile, x)));
}
function to_candid_ContactRequest_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactRequest): _ContactRequest {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_CouponType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CouponType): _CouponType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Coupon_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Coupon): _Coupon {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LoyaltyAction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoyaltyAction): _LoyaltyAction {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_PortfolioItem_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortfolioItem): Promise<_PortfolioItem> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_Product_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    category?: string;
    image: ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    description: string;
    category: [] | [string];
    image: _ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        category: value.category ? candid_some(value.category) : candid_none(),
        image: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.image)
    };
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    requiresQuote: boolean;
    inStock: boolean;
    name: string;
    description: string;
    category?: string;
    image: ExternalBlob;
    price: bigint;
}): Promise<{
    id: string;
    requiresQuote: boolean;
    inStock: boolean;
    name: string;
    description: string;
    category: [] | [string];
    image: _ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        requiresQuote: value.requiresQuote,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        category: value.category ? candid_some(value.category) : candid_none(),
        image: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    validFrom: Time;
    code: string;
    discountType: CouponType;
    usageCount: bigint;
    usageLimit?: bigint;
    validUntil: Time;
}): {
    active: boolean;
    validFrom: _Time;
    code: string;
    discountType: _CouponType;
    usageCount: bigint;
    usageLimit: [] | [bigint];
    validUntil: _Time;
} {
    return {
        active: value.active,
        validFrom: value.validFrom,
        code: value.code,
        discountType: to_candid_CouponType_n19(_uploadFile, _downloadFile, value.discountType),
        usageCount: value.usageCount,
        usageLimit: value.usageLimit ? candid_some(value.usageLimit) : candid_none(),
        validUntil: value.validUntil
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    loyaltyPoints: bigint;
}): {
    name: string;
    email: [] | [string];
    loyaltyPoints: bigint;
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        loyaltyPoints: value.loyaltyPoints
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    projectType?: string;
    name: string;
    submittedAt: Time;
    submittedBy: Principal;
    description: string;
    productId?: string;
    email: string;
    budget?: string;
    timeline?: string;
}): {
    id: string;
    status: string;
    projectType: [] | [string];
    name: string;
    submittedAt: _Time;
    submittedBy: Principal;
    description: string;
    productId: [] | [string];
    email: string;
    budget: [] | [string];
    timeline: [] | [string];
} {
    return {
        id: value.id,
        status: value.status,
        projectType: value.projectType ? candid_some(value.projectType) : candid_none(),
        name: value.name,
        submittedAt: value.submittedAt,
        submittedBy: value.submittedBy,
        description: value.description,
        productId: value.productId ? candid_some(value.productId) : candid_none(),
        email: value.email,
        budget: value.budget ? candid_some(value.budget) : candid_none(),
        timeline: value.timeline ? candid_some(value.timeline) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "fixed";
    fixed: bigint;
} | {
    __kind__: "percentage";
    percentage: bigint;
}): {
    fixed: bigint;
} | {
    percentage: bigint;
} {
    return value.__kind__ === "fixed" ? {
        fixed: value.fixed
    } : value.__kind__ === "percentage" ? {
        percentage: value.percentage
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "visit";
    visit: null;
} | {
    __kind__: "share";
    share: null;
} | {
    __kind__: "signup";
    signup: null;
} | {
    __kind__: "purchase";
    purchase: bigint;
}): {
    visit: null;
} | {
    share: null;
} | {
    signup: null;
} | {
    purchase: bigint;
} {
    return value.__kind__ === "visit" ? {
        visit: value.visit
    } : value.__kind__ === "share" ? {
        share: value.share
    } : value.__kind__ === "signup" ? {
        signup: value.signup
    } : value.__kind__ === "purchase" ? {
        purchase: value.purchase
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
